### ISSUE TITLE
Decide on the endpoints structure

### ISSUE THREAD

**Issue by iwoork** [findthecluster/api-app#10]
Here's my proposal for the endpoints:

**Option 1**: Separate a **Report** and **Probability** endpoints
- The Report endpoint will simply save self-reported information
- The Probability endpoint accepts self-reported symptoms as parameter and outputs a probability from data science

**Option 2**: Combine **Report** and **Probability** as one endpoint
- POSTing a data to /report will not only save the submitted report but will also send back a response which includes the probability

**Comment by rashnil-git** [comment]
Option 1 was what I had in my architecture diagram. I prefer one as it makes the api lightweight and asynchronous. Client can just push the data and api can work on storing that. Otherwise if there are DB related issues, it will delay the stats response as well. client can make asynchronous calls to api endpoints and get the results back from probability endpoint.

**Comment by rashnil-git** [comment]
Also it will allow us to have different configurations for different types of workload and use cases.

**Comment by iwoork** [comment]
Let's go for Option 1. I guess call it 'Assess' or 'Probability' makes more sense?

`POST /assess`

**Comment by rashnil-git** [comment]
How about:

Endpoint 1 for submission:

`POST /survey`

Endpoint 2 for probability:

`POST /stats`?

**Comment by iwoork** [comment]
Sounds good. Let's do that.

**Comment by rashnil-git** [comment]
I have added tickets in project board. I will have them ready by this weekend.

**Comment by rashnil-git** [comment]
End Points created.

/stats : https://github.com/findthecluster/api-app/issues/12

**Comment by rashnil-git** [comment]
/survey endpoint : https://github.com/findthecluster/api-app/issues/11

**Comment by rashnil-git** [comment]
Wiki Page : https://github.com/findthecluster/api-app/wiki
